import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import { Platform } from 'react-native';

export async function shareHtmlPdf(html: string, filename = 'byajwala.pdf') {
  try {
    const { uri } = await Print.printToFileAsync({ html });
    if (Platform.OS === 'web') {
      await Print.printAsync({ html });
      return;
    }
    if (await Sharing.isAvailableAsync()) {
      await Sharing.shareAsync(uri, { UTI: '.pdf', mimeType: 'application/pdf', dialogTitle: filename });
    } else {
      await Print.printAsync({ uri });
    }
  } catch (e) {
    console.warn(e);
    throw e;
  }
}

export function receiptHtml(p: {
  business: string;
  receipt_no: string;
  customer: string;
  loan_no: string;
  date: string;
  amount: string;
  interest: string;
  principal: string;
  remainP: string;
  remainI: string;
  mode: string;
  remarks: string;
}) {
  return `<html><body style="font-family:system-ui;padding:24px;color:#1B2430">
  <h2 style="color:#0F4C81">${escapeHtml(p.business)}</h2>
  <p>Payment receipt</p>
  <table style="width:100%;border-collapse:collapse">
  ${row('Receipt', p.receipt_no)}${row('Customer', p.customer)}${row('Loan', p.loan_no)}
  ${row('Date', p.date)}${row('Amount', p.amount)}${row('Interest paid', p.interest)}
  ${row('Principal paid', p.principal)}${row('Remaining principal', p.remainP)}
  ${row('Remaining interest', p.remainI)}${row('Mode', p.mode)}${row('Remarks', p.remarks)}
  </table>
  <p style="color:#6B7785;font-size:12px;margin-top:24px">Generated by ByajWala · offline</p>
  </body></html>`;
}

export function statementHtml(title: string, bodyRows: string) {
  return `<html><body style="font-family:system-ui;padding:24px">
  <h2 style="color:#0F4C81">${escapeHtml(title)}</h2>
  ${bodyRows}
  </body></html>`;
}

function row(k: string, v: string) {
  return `<tr><td style="padding:6px;border-bottom:1px solid #eee;color:#6B7785">${escapeHtml(k)}</td>
  <td style="padding:6px;border-bottom:1px solid #eee;text-align:right">${escapeHtml(v)}</td></tr>`;
}

export function escapeHtml(s: string) {
  return String(s ?? '').replace(/[&<>"]/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' }[c]!));
}

export function toCsv(headers: string[], rows: (string | number)[][]) {
  const esc = (x: any) => `"${String(x).replace(/"/g, '""')}"`;
  return [headers.map(esc).join(','), ...rows.map((r) => r.map(esc).join(','))].join('\n');
}
